### ISSUE TITLE
RE: Infamous Launcher 

### ISSUE THREAD

**Issue by ghost** [infamouscheats/InfamousCheats#1]
The infamous launcher is failing Benny.  The error is "the underlying connection was closed" Could not establish trust relationship for the SSL/TLS secure channel. What is this error? do you know how I can fix it?
![screenshot 1](https://user-images.githubusercontent.com/38597776/39101006-cbd86350-46d6-11e8-8349-46ac18c73ca2.png)

**Comment by TheSparctan** [comment]
this is what i found. good luck.

https://success.outsystems.com/Support/Enterprise_Customers/Troubleshooting/%22Could_not_establish_trust_relationship_for_the_SSL%2F%2FTLS%22_error

**Comment by rickles80** [comment]
Is your menu working? And id this really Benny from Infamous on this website?

**Comment by TheSparctan** [comment]
No my menu is not working, I actually dont even have the files anymore. And
yeah it is from what i can tell, This github page redirected from the
infamous website

**Comment by rickles80** [comment]
Ok, I have the launcher 2.5.4.23 if you need it

**Comment by TheSparctan** [comment]
Yeah let me have a go at getting it to work. Who knows.

**Comment by rickles80** [comment]
Man, I've tried everything. resetting firewall, internet & disabling antivirus. I think its failing to connect to their server some how, idk

**Comment by TheSparctan** [comment]
I think theres a chance thier server is totally down and Benny is waiting to get it back up. I think the error is on thier end somehow.

**Comment by Josef-1** [comment]
Can I also have a look at the launcher, I'll see if it works for me.

**Comment by rickles80** [comment]
I think so too. I hope its up & running soon. Since the menu went down I have had modders trapping me in cages, setting me on fire, blowing up my ride & ****ing me in the ass literally

**Comment by rickles80** [comment]
Josef, idk how to upload it here so you can download it

**Comment by Josef-1** [comment]
Just drag the launcher into the comment box.

**Comment by TheSparctan** [comment]
Oh yeah GTA Online is hell now, And theres no safe alternative to Infamous. 

And you can just drag and drop the files here but ehhh I think this is public

**Comment by Josef-1** [comment]
You can delete it afterwards

**Comment by rickles80** [comment]
Doesnt support the file type bro

**Comment by TheSparctan** [comment]
Because its a folder
Upload it to Google drive and share the link here (view only)

**Comment by rickles80** [comment]
i'll do that

**Comment by rickles80** [comment]
https://drive.google.com/file/d/1sfDTWK1R4YZueWP8sxfF9KnfuWkzV9ai/view?usp=sharing

**Comment by rickles80** [comment]
Try this

**Comment by TheSparctan** [comment]
"The remote hostname could not be resolved: infamouscheats.cc"

**Comment by rickles80** [comment]
I get that error also sometimes

**Comment by Josef-1** [comment]
I get that error, seems like their authenticator is down.

**Comment by TheSparctan** [comment]
Here im hosting a Discord server. 
https://discord.gg/DxJWQTr
Lets talk here.

**Comment by rickles80** [comment]
I just wish that someone from infamous would be so kind as to let us know. Clarity would be nice at this point

**Comment by TheSparctan** [comment]
Yeah. Stuff like this happens when the menus get a C&D or other legal action

**Comment by rickles80** [comment]
Hang on, i need to re-install discord, just got a new M.2

**Comment by TheSparctan** [comment]
Alright @rickles80

**Comment by Thenecromance** [comment]
u cant fix it.

**Comment by ghost** [comment]
Seems R* is targeting externals now. Aimware is getting tickled right now

**Comment by dequeues** [comment]
@morda75 What do you mean? They're still selling it?

**Comment by infamouscheats** [comment]
There has been another update.
