### ISSUE TITLE
Username/password always wrong

### ISSUE THREAD

**Issue by benny593** [infamouscheats/InfamousCheats#10]
I just reset my Windows (my HWID didn't change at all), I am pretty sure I entered the correct password and username, but it always return the wrong username and password error to me. Why is that?

**Comment by ghost** [comment]
If you deleted your appdata folder you're screwed.

**Comment by benny593** [comment]
So GG? That's the end of line for me?

**Comment by ghost** [comment]
More than likely.

**Comment by infamouscheats** [comment]
Yes, you must have accessed the server prior to the downtime.  It is still up for a few users who had access and kept their appdata files.
