### ISSUE TITLE
GTA crashing before it even started

### ISSUE THREAD

**Issue by jWXZSCsqrpZRSVwauBjn** [infamouscheats/InfamousCheats#11]
After a Windows-Update my GTA crashes before the intro appears. It were working fine for a long time before.
These are the things I already tried:
-checked Windows with sfc /scannow
-verified game files
-tried to start it with another copy of the launcher
-deleted the config db in %appdata% and my game settings

Wondering if anybody is experiencing the same problem or has a fix it

**Comment by ghxost** [comment]
Downgrade to the last build...? It is likely your drivers though. I've ran this with GTA on every major release build and most of the recent preview builds without issue

**Comment by infamouscheats** [comment]
Does the game start without using the launcher?

**Comment by jWXZSCsqrpZRSVwauBjn** [comment]
Yes, I can start it. If I try to inject while in-game, it takes like 1 minute until "verification" at the bottom right appears. Then it authenticates and after it says "ready", it crashes. There's no information in the log. Compared it with another guy

**Comment by ghxost** [comment]
First: Disable AV and windows defender - I do defender via registry so it doesn't turn back on after 10 minutes...
I'm on 17686 without issue (win 10 preview build) - ran fine from 1603? to now
It  has to be some compatibility thing though for you
I'd update all your base drivers
Check simple things like vram and performance settings
Check nvidia panel if applicable (max performance vs power etc.)
Fullscreen? Seems to work 100% for me on fullscreen...
Reinstall redistributes (all of them) - uninstall and reinstall if needed
Reset gta graphics to default? Last resort - it never gets anything right and is a PITA... Doubt it would help anyway based on the info...

Good luck :)

**Comment by jWXZSCsqrpZRSVwauBjn** [comment]
Reinstalling the redistributes worked. Thanks @ghxost!
