### ISSUE TITLE
what/where can I get infamous? I have the lifetime membership but the old infamous page doesn't work anymore 

### ISSUE THREAD

**Issue by jayman1000** [infamouscheats/InfamousCheats#12]

**Comment by ghxost** [comment]
There are some unofficial links around, some on the posts here for a newer build

You must still have your (not someone elses) appdata and you had to have logged in while the server was still up to get the files needed in your appdata for offline (auth offline, not gta...) play.

Good luck :)

**Comment by jayman1000** [comment]
Thanks, but it just says wrong password/username. But it's the same \AppData\Roaming\Infamous GTAV Menu folder with the old username and password stored, no changes made; on the same computer. I had bought the lifetime membership, Platinum I believe it was called. So that kinda sucks :/

**Comment by ghost** [comment]
Where does it say wrong password? Because the server is not even up to check your password.. do you have an auth.dat file in your appdata folder?

**Comment by jayman1000** [comment]
It says wrong password/username after loading into story mode.
But there is no auth.dat file no, so that's the problem? They must have not used that file in the version I had installed and used back then.

**Comment by ghost** [comment]
Yep you need the auth.dat file now

**Comment by holyr00d** [comment]
run recuva asap for appdata folder and see if it pulls it for you. sort list alphabetically

**Comment by infamouscheats** [comment]
Yes, you need to have accessed the server prior.

**Comment by holyr00d** [comment]
@infamouscheats anyway to contact you privately?

pgp be ok?

**Comment by ghxost** [comment]
For real, me too, I want some infamous shwagg dawg
Just kidding, I'm sure he had a good reason though...

**Comment by infamouscheats** [comment]
pgp is OK.  Infamouscheats@protonmail.com

**Comment by infamouscheats** [comment]
Sorry everyone.  I can't really comment about the subjects you all emailed.  Certain criteria need to be maintained in order for original users to be able to connect to auth.  I can't get much more specific about it.

**Comment by Exophobias** [comment]
@infamouscheats Will Infamous ever be updated again? I know you don't know much about the future of inf but can we all get some sort of hint or nudge to know which way the scale drops. Many expect that inf may never come back again or will come back in a year or two. 
Do you have any sort of ETA or something (truthful of course) that will keep our hopes up for inf?

If you don't want to say it on here, can you email me or someone else about it?

**Comment by ImGrayy** [comment]
Don't think Ben is allowed to legally.

**Comment by Exophobias** [comment]
@infamouscheats Would there be any repercussions if we were to chargeback? if inf comes back can we repurchase inf again and go about our day?

**Comment by ghxost** [comment]
You paid for a service for the life of that service. You used it all you
wanted while you could.

Chargeback now? Dick move...

JMHO as a user

**Comment by Exophobias** [comment]
The only reason I was saying that is because I bought Infamous March 8th – In all honesty, I didn’t get much out of the service except a bit of fun and of course the balance. The lifetime of inf wasn’t long for me. Which disappoints me and of course I knew it was coming just not so soon.

________________________________
