### ISSUE TITLE
Reinstalling system, things to have in mind, backups of Infamous Menu.

### ISSUE THREAD

**Issue by coruptcitizen** [infamouscheats/InfamousCheats#13]
Hi Benny. Im planning to format my pc. What files/folders must I back up in order to still be able to use the menu?

**Comment by jWXZSCsqrpZRSVwauBjn** [comment]
You'll need the infamous folder with the auth.dat and the launcher. But I think your HWID will change after reinstalling windows.
You could try a HWID changer

**Comment by coruptcitizen** [comment]
the infamous folder does not have the auth.dat, only the launcher. why

**Comment by ImGrayy** [comment]
@coruptcitizen Wrong folder. Go to Users in windows explorer > your PCs name > App data (will need to enable hidden files > http://prntscr.com/jvpwnz ) > Roaming then Infamous GTAV Menu.

Also yes, you can update your PC and do all the normal stuff besides resetting it. DO NOT reset your PC if you wish to continue to use Infamous. IMO you should no longer be using it as an update for GTA V is going to be coming out soon and it may become detected.

**Comment by infamouscheats** [comment]
Just as some words of advice, a reinstall on your end will change the authorization we have set up.  I can't get into specifics but you will encounter errors of validation on the auth server.  A new update "nightclubs" or similar, from the game company, will be happening during this month.

**Comment by ghxost** [comment]
I'm really really trying to read between the lines there that maybe those authed will get an update for the next dlc... what a stretch, oye.

**Comment by coruptcitizen** [comment]
ok, i will not format my pc for now, thnaks for the assistance
