### ISSUE TITLE
Why are other private hacks still online?

### ISSUE THREAD

**Issue by holyr00d** [infamouscheats/InfamousCheats#16]
why are other menus still online on clearnet. another menu appears to have gotten most of infamous users.

cant infamous guys set up shop on an onion address?

**Comment by holyr00d** [comment]
that easy? look at the drug markets.... fbi, cia, gchq etc all cant find their servers or shut down their onion addresses. So yeah i think it would be quite easy for them. silk road was an exception. hired help cost millions. i dont think take2 would take it that far.

not all of the other menus. only one i know of that has went offline from the web, literally. is infamous.

**Comment by ghxost** [comment]
I named two popular others already and know of at least 5 more just like
them. The devs all like programming and money. Why did they all leave?
Obviously it is not as straight forward once you gain the attention. Seems
much easier to start from scratch with an illegitimate product and go
underground from the start. Quite a different thing for an established
brand with customers, especially after being legally targeted already. The
penalties are much more harsh if you get caught (again)
