### ISSUE TITLE
Where can i download the launcher?

### ISSUE THREAD

**Issue by ZEEF1337** [infamouscheats/InfamousCheats#2]
I had premium access (The expensive lifetime one), but have formatted my PC, so i've lost my launcher, i was kinda hoping i could download it here, but i can't see anything in the repository, so i was wondering where can i download the launcher? :)

**Comment by infamouscheats** [comment]
Looks like the previous version (2.5.4.23) has been uploaded in it's entirety to se7ensins.  I would download that file, use the launcher and get the updated files from that.  We have to wait until there is proper authority on this github account to post repositories.  

https://www.se7ensins.com/forums/threads/infamous-down.1712684/#post-13572243

**Comment by ghxost** [comment]
Is the 2.5.5.23 version essentially ok (launcher version 2.42.0.0)? Got it before the downtime...

**Comment by infamouscheats** [comment]
2.5.5.23 is the correct version.

**Comment by ZEEF1337** [comment]
![screenshot_1](https://user-images.githubusercontent.com/34263775/39245392-edb29da6-4893-11e8-9162-a782783f11e1.png)
I keep getting this error, i've launched the launcher (Infamous Lanucher.exe) as admin, it did a quick update the first time, but i keep getting this error (Using the files linked above) :/

**Comment by infamouscheats** [comment]
I would delete files (zip and in %appdata) and try again.  It should call for the right files automatically.

**Comment by ZEEF1337** [comment]
I tried to remove all the files except Infamous Launcher, but same issue (Cleared appdata aswell) I have the launcher version 2.42.0.0 but in the log file it says "Version: 2.5.4.23" And above you said "2.5.5.23 is the correct version" 😮

**Comment by infamouscheats** [comment]
2.5.4.23 will be updated to 2.5.5.23 with the launcher 2.42.  Not sure what your situation is with your PC.  Try to start from scratch with the whole thing.  If that doesn't work, wait for an update.
