### ISSUE TITLE
Black screen for doomsday finale screen only when being the host and using inf

### ISSUE THREAD

**Issue by ghost** [infamouscheats/InfamousCheats#3]
Hello, 
 
When not using inf and hosting the finale myself, the screen appears as per normal. 
When joining other hosts for doomsday heist finales, their finale screens appear as per normal. 

It's probably one of my settings I'm not sure of.. but I encounter black screens when I'm hosting and using inf. Looking for a solution please and thank you. 
 
Kind regards, 
MilesUnderYou

**Comment by ImGrayy** [comment]
this could possibly be an issue with yourself and not inf. what's your NAT type? check by going into home page in gta then settings then network statistics.

**Comment by ghost** [comment]
NAT type is moderate

**Comment by ghxost** [comment]
Had this issue with another product
Workarounds as follows:

Exit setup screen and restart the heist finale screen again - it typically will work the second time around
Memorize the setup screen and know which buttons you need to press to proceed - input is recognized and you will see the rest of the heist just fine

Again, from another product, but same issue... Was never fixed but these workarounds always worked for me
I'm a ways off form the finale right now but I'll give these a try myself when I get there again to see if it is the same, or post back :)

**Comment by ghost** [comment]
Thanks for that but was fooling around and doing some trial-and-error while waiting for a solution and possibly found myself a quick fix. 
Issue was indeed probably with my NAT/Network 
(distance from servers or whatever idk what the actual tech terms are) 
 
My workaround was: 
Staying in that session for a period of time before starting it OR 
Exit facility, stay in freemode for approx. 5 minutes, go back into facility, run to heist room and start it. 
 
Will close this since I've found a solution. The ^ help is appreciated nonetheless :D 
 
Kind regards, 
MilesUnderYou
