### ISSUE TITLE
inf user banned?

### ISSUE THREAD

**Issue by ImGrayy** [infamouscheats/InfamousCheats#4]
hey benny, i have an inf user that was supposedly banned from using it. he said he didn't do anything bad, such as recoveries and what not. he just signed into multiple accounts that he owns. his inf username is SodaShark if you can look into it possibly. if you want paypal transactions i can also post those as well.

**Comment by ImGrayy** [comment]
also wanted to add on. there's a lot of 404 auth issues going on with users. redl inf, deleted %appdata%, antiviruses disabled completely. if you know anything about this i'll relay it to the chat we are in.

**Comment by Exophobias** [comment]
A lot of people are also having black and blank inf consoles. No writing is shown and its black rather than blue and doesn't work whatsoever.
He read the readme and has all the Visuals installed and such.
