### ISSUE TITLE
Never Wanted for Other Players

### ISSUE THREAD

**Issue by Exophobias** [infamouscheats/InfamousCheats#6]
Could you please add Never Wanted to for other players back. Its not griefing/trolling in any way. Its great for when me and my friend want to go mess around and don't want to deal with the cops. It was something he really enjoyed and I also enjoyed it because I didnt have to kill cops or have my car smashed in to.

**Comment by ghxost** [comment]
Just have them hop in your car, should get rid of their wanted level.

**Comment by ImGrayy** [comment]
Don't think that's exactly true, I'm not 100% sure though. I always have never wanted on and when my friends get into my cars and they get cops I noticed they still chase us.

**Comment by infamouscheats** [comment]
Once you get your friends in the car, you have to toggle "never wanted" off and on again.  Only then will your friends wanted level disappear.

**Comment by Exophobias** [comment]
I liked the ability to do it remotely if we are in different vehicles though. That way we can go do bad things together in different vehicles.
With the new updates, is it causing issues having that feature because they aren't protected by the methods of INF?

**Comment by ghxost** [comment]
I have no issues messing about with friends ::shrugs::

**Comment by Exophobias** [comment]
My never wanted won't remove my friends wanted level.

**Comment by ghxost** [comment]
Works for me and anyone I ride with

Shrugs....
