### ISSUE TITLE
Infamous Error 

### ISSUE THREAD

**Issue by ghost** [infamouscheats/InfamousCheats#8]
So basically I get this error every time I log into the launcher and open my game. 
And of course I am a Premium lifetime member. This error started to happen some weeks ago. I've tried on different PC's and none of them worked for me. Deleted the ZIP file and cleared the Infamous %appdata%. 

If anyone finds a fix for this issue feel free to reply on this thread. I will update the thread if I manage to fix the issue myself. 

![39245392-edb29da6-4893-11e8-9162-a782783f11e1](https://user-images.githubusercontent.com/39219186/39958504-40600e58-5604-11e8-838e-351f5e24059f.png)

**Comment by HowieForrest** [comment]
Me too, version 2.5.4.23

**Comment by ghxost** [comment]
2.5.5.23 is still working for me
Hopefully the updated launcher will be reposted...
I don't work here :D

**Comment by holyr00d** [comment]
can someone please share latest launcher? fellow plat user

**Comment by ghxost** [comment]
I would, with permission... Not mine to distribute though

**Comment by holyr00d** [comment]
nevermind, I found it.

**Comment by holyr00d** [comment]
@ghxost what is the date modified of your .dll?

**Comment by ImGrayy** [comment]
launcher will only work if you got the latest patch before the servers went down, must be something in reg causing this to happen if you give someone else your inf. i'll check it out later

**Comment by ghxost** [comment]
Nothing stopping an anonymous post from someone on a VPN over an unsecured wireless connection, I mean anyone can join here...
That being said, I'm happy it is what it is, even just until the next DLC update or whatnot if it cripples the project.
It's been a hell of a ride! No hard feelings here :D

**Comment by holyr00d** [comment]
@ghxost you are not running the latest menu.

sorry dont wanna copy and paste post. see here 

https://infamousmenu.com/index.php?threads/infamous-menu-an-update.20/

anyone tested this?

https://github.com/GODZGamingNetwork/InfamousCheats_2.5.5.23

states master file. from apache server.... appears legit...

**Comment by ImGrayy** [comment]
https://infamousmenu.com is obviously not a legit website. They're not anyway associated with the Inf staff, as far as we are aware of according to their information page. I'm not sure why they're running a forum and I'm not sure how long it will last.

**Comment by holyr00d** [comment]
@ImGrayy i never said that site was legit. it is a site to discuss the menu. I was referring to godsgamingnetwork launcher pack

**Comment by ghxost** [comment]
What I have is the latest in my repository. I have all versions going back aways, including 2.5.5.13. But why use an older build? Even if the modified date is different, versions rise, so newer would be higher unless the devs were very tired that day.
The only 'bug' I have is with the modder tag, which is a non-issue. If there is any reason not to use 2.5.5.23 for now I'd love to hear it.

I would not launch anything from any unofficial source. You never know what could have been done to it. You could be passing along your login info to anyone. Same goes for random forums, hope you all are using unique passwords :x

**Comment by holyr00d** [comment]
the menu is not an old build though with .13 launcher. other than the bug stated there is no other problems with .23 they both work. .13 menu is most recent though. the date of the dll says so. i am sure you have seen the difference between them. it is debranded and does not display your username either. ..
I never got .13 or .23 from an unofficial source. 

godzgamingnetwork one i am curious about though. it has come from an apache server all the files appear legit in regards with matching up with .13 and .23 files, size etc just all the files date modified reads 13.5.2018 which seems out of ordinary as all the files have never had the same date ever in any of the menu downloads.

**Comment by ImGrayy** [comment]
i've searched the reg up and down, nothing related to logins and specials that keep other users or current inf users without a working %appdata% file from using inf. only option is just to wait for the server to come back online, if the inf devs will even be coming back.

edit:

also it's kind of odd with that download of in being modified so recently. i wouldn't trust it for a second, it's still outdated because it does not have the latest features before the servers went down.

**Comment by Ceiridge88** [comment]
Try using Procmon

**Comment by ImGrayy** [comment]
@Ceiridge yes, i have. there's only 2 locations of inf.

**Comment by ghost** [comment]
@ImGrayy Its the auth.dat file in the appdata folder.. you need that or it wont work. I'm 99% sure the auth.dat file is tied to your hwid as well.

**Comment by ImGrayy** [comment]
yea i read something about that as well, it does suck but it's whatever. it's a good break from the game.

**Comment by holyr00d** [comment]
auth is not tied to hwid. i have deleted that folder twice once for 2.5.4 and 2.5.5.13 both of which still updated.

tested https://github.com/GODZGamingNetwork/InfamousCheats_2.5.5.23 works fine cmd prompt identical to others.

I mixed up some files from .13 and .23. added .13 dll (newest date modified) to .23 and all loaded up correctly. so running latest menu with latest .exe and launcher.

**Comment by ghost** [comment]
@R00dNet I guarantee if you delete the appdata folder now you won't be able to get the menu back, I also guarantee that if you transfer the appdata folder and the rest of your inf files to a new pc it won't work. I've tested all of this.

**Comment by holyr00d** [comment]
how did you test delete auth.dat on your machine since menu server has been offline?

the files within that folder are generated upon successful login/authentication. i fail to see why a legit login would not authenticate if the server comes back online due to any of the files having been replaced in the appdata folder. legit login will always grab latest files from server and authorise via hwid.

shame it never loaded on another machine, this i was curious to know. again points to hwid being true identifier of account. did the launcher download latest launcher before authentication commenced? did the appdata folder generate any files from the login? infamous or launcher folder?

**Comment by ghost** [comment]
I didn't actually delete it, I just moved it out of the appdata folder and tried it. And yes if the server ever comes back online them i'm sure everyone with a valid login will be able to use it again but for now you need the correct auth.dat file for your machine because the authentication fully relies on that now from what I can see. 
The launcher doesn't download anything now it just gives a server error.

**Comment by holyr00d** [comment]
you are right. sorry for doubting you.

**Comment by ghxost** [comment]
And here I am running the latest Windows preview build without a backup
High risk, no reward
Time to make a backup? lol
Thanks for the info everyone!

**Comment by holyr00d** [comment]
potential update (maintenance) on 12th june. so we will see if manu gets an update or not few days after.

**Comment by ImGrayy** [comment]
I doubt it. They are still in court about the threat Take-Two has given them. Currently seems like a war between Infamous vs Take-Two and R* at the moment.

https://www.pacermonitor.com/public/case/24131026/TakeTwo_Interactive_Software,_Inc_v_Cameron_et_al

link if no one else has seen it yet (mentions of Chris and Infamous, so yes it is them)

**Comment by infamouscheats** [comment]
Auth is, and has been, very strict in the past months.  While this process is ongoing, only users with prior access before the downtime are able to continue to access the package on the server.  Do not try and run from an unofficial source.  You risk a lot and it only takes one time to get a bad outcome.

**Comment by ghxost** [comment]
I hope and pray for one more update (more would be nice obviously) but I feel one is forthcoming in GTA
If nothing else do the people who are able to run it now have a better chance of an update?
Or is an all or none thing at that point - like a decision is made once and for all after the next GTA update?

If you cannot answer no biggie. I just figure it is one of the two. Luckily I'm in camp A so I hope for that at the least. I understand the 'all or nothing' approach is more fair though haha

**Comment by infamouscheats** [comment]
As of now, the group who are auth'd in are going to receive any update the launcher fetches.  As for all of the other users, downtown is indefinite.  I wish I had a more concrete answer.

**Comment by jWXZSCsqrpZRSVwauBjn** [comment]
But there won't be updates while the lawsuit is going on, right?

**Comment by infamouscheats** [comment]
I'm sorry, I should've been clearer on that last comment.  Updates are also indefinite.  I can't comment on that either way (yes or no) as of the moment.

**Comment by holyr00d** [comment]
i really hope an update happens at least in part to maintain the anti-grief features. if or when need be.

**Comment by holyr00d** [comment]
well next game update going to be in july. see you on the dancefloor ;)

**Comment by holyr00d** [comment]
@infamouscheats game wont allow menu. single player just crashes game does not get past waiting for window to load. if an update happens please mention to have option to have menu run silent without browsing sounds.

**Comment by holyr00d** [comment]
@infamouscheats sent you mail from my proton account, forgot i had it.

utu
