### ISSUE TITLE
Future

### ISSUE THREAD

**Issue by jWXZSCsqrpZRSVwauBjn** [infamouscheats/InfamousCheats#9]
Will there be any Updates in the next time or do we just need to be patient?
It's really annoying not to know how you guys will go ahead. 
If there's no chance that it'll come back just set a clear ending. Nobody will blame you for it. You always tried to give your best for us and I think everybody will accept your decision.

**Comment by ImGrayy** [comment]
There's a possibility they can not talk with us, legally.

**Comment by ghxost** [comment]
Meant to post here, see comment other thread :P

**Comment by infamouscheats** [comment]
I am able to comment on some things.  The future for INF is unknown at this very moment.

**Comment by Exophobias** [comment]
When GTA V updates, will there be a patch released either through the updater or by other means of download? Many can not use it and will want to use it once GTA is updated.

We still got faith in you Benny, we actually have a small Discord for inf peoples so we can figure out whats going on and spread news of Inf. A lot of people things its gone forever.

**Comment by ghxost** [comment]
Could be, especially after the next update. I think things are clear if you read through all the threads and replies.
Hopefully we'll see that long awaited update after gta update drops. If not, we'll know it was not so good news or still a waiting game at the least.
